FROM golang:alpine as build-env

ENV GO111MODULE=on

RUN apk update && apk add bash ca-certificates git gcc g++ libc-dev

RUN mkdir /docker_chat
RUN mkdir -p /docker_chat/proto

WORKDIR /docker_chat

COPY ./protos/service.pb.go /docker_chat/protos
COPY ./main.go /docker_chat

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN go build -o docker_chat .

CMD ./docker_chat
